# Generated by Django 3.2 on 2021-08-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tienda',
            name='idPersona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyectoAPI.persona'),
            preserve_default=False,
        ),
    ]
